{
 "title": "Node Exporter 0.17.0 (Host Metrics)",
 "description": "Dynamic Dashboard covering metrics for: 1 VM, n VMs or All VMs.\n",
 "tags": [
  "grafana",
  "prometheus",
  "noe_exporter 0.17"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "host", "label": "Host", "query": "label_values(alias)" },
   {
    "name": "version",
    "label": "Exporter Version",
    "query": "label_values(node_exporter_build_info,version)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Exporter",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "count(node_exporter_build_info{alias=~\"$host\"}) by(alias,env,instance,version)"
      }
     ]
    },
    {
     "title": "Uptime (time)",
     "type": "graph",
     "description": "UPTIME: measures the time from the last reboot/ power on of the server till now.\n>Uptime < 1min means that the VM was rebooted 1 min ago.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "node_time_seconds{alias=~\"$host\"} - node_boot_time_seconds{alias=~\"$host\"}",
       "legendFormat": "Uptime: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load1%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Downtime",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg_over_time(up{alias=~\"$host\"}[1d]) < 1",
       "legendFormat": "Downtime: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load1%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
      }
     ]
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kernel",
     "type": "table",
     "description": "Uname",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "count(node_uname_info{alias=~\"$host\"}) by (alias,env,instance,machine,release)"
      }
     ]
    },
    {
     "title": "Interrupts",
     "type": "graph",
     "description": "- Processors can be orders of magnitudes faster than the hardware they talk to; it is not ideal for the kernel to issue a request and wait for a response from slower hardware. Instead, the kernel must be free to go and handle other work, dealing with the hardware only after that hardware has actually completed its work. \n\n- How can the processor work with hardware without impacting the machine's overall performance? As one solution, polling incurs overhead, because it must occur repeatedly regardless of whether the hardware is active or ready. A better solution is to provide a mechanism for the hardware to signal to the kernel when attention is needed. This mechanism is called an interrupt. This chapter dicusses interrupts and how the kernel responds to them, with special functions called interrupt handlers.\n\n- Interrupts\n  - Interrupts enable hardware to signal to the processor.\nFor example, as you type, the keyboard controller (the hardware device that manages the keyboard) issues an electrical signal to the processor to alert the operating system to newly available key presses. These electrical signals are interrupts. The processor receives the interrupt and signals the operating system to enable the operating system to respond to the new data.\n  - Hardware devices generate interrupts asynchronously (with respect to the processor clock). Consequently, the kernel can be interrupted at any time to process interrupts.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(node_intr_total{alias=~\"$host\"}[$__range])",
       "legendFormat": "Interrupts: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "graph",
     "description": "- In computing, a context switch is the process of storing the state of a process or of a thread, so that it can be restored and execution resumed from the same point later. This allows multiple processes to share a single CPU, and is an essential feature of a multitasking operating system.\n\n - The precise meaning of the phrase “context switch” varies significantly in usage. In a multitasking context, it refers to the process of storing the system state for one task, so that task can be paused and another task resumed. A context switch can also occur as the result of an interrupt, such as when a task needs to access disk storage, freeing up CPU time for other tasks. Some operating systems also require a context switch to move between user mode and kernel mode tasks. The process of context switching can have a negative impact on system performance, although the size of this effect depends on the nature of the switch being performed.\n\n - Context switches are usually computationally intensive, and much of the design of operating systems is to optimize the use of context switches. Switching from one process to another requires a certain amount of time for doing the administration – saving and loading registers and memory maps, updating various tables and lists, etc. What is actually involved in a context switch varies between these senses and between processors and operating systems. For example, in the Linux kernel, context switching involves switching registers, stack pointer, and program counter, but is independent of address space switching, though in a process switch an address space switch also happens. Further still, analogous context switching happens between user threads, notably green threads, and is often very light-weight, saving and restoring minimal context. In extreme cases, such as switching between goroutines in Go, a context switch is equivalent to a coroutine yield, which is only marginally more expensive than a subroutine call.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(node_context_switches_total{alias=~\"$host\"}[$__range])",
       "legendFormat": "Context Switches: {{alias}}"
      }
     ]
    },
    {
     "title": "Forks",
     "type": "graph",
     "description": "- Fork\n  - When you come to metaphorical \"fork in the road\" you generally have two options to take, and your decision effects your future. Computer programs reach this fork in the road when they hit the fork() system call.\n\n  - At this point, the operating system will create a new process that is exactly the same as the parent process. This means all the state that was talked about previously is copied, including open files, register state and all memory allocations, which includes the program code.\n\n  - The return value from the system call is the only way the process can determine if it was the existing process or a new one. The return value to the parent process will be the Process ID (PID) of the child, whilst the child will get a return value of 0.\n\n   - At this point, we say the process has forked and we have the parent-child relationship as described above.\n\n- Exec\n  - Forking provides a way for an existing process to start a new one, but what about the case where the new process is not part of the same program as parent process? This is the case in the shell; when a user starts a command it needs to run in a new process, but it is unrelated to the shell.\n\n  - This is where the exec system call comes into play. exec will replace the contents of the currently running process with the information from a program binary.\n\n  - Thus the process the shell follows when launching a new program is to firstly fork, creating a new process, and then exec (i.e. load into memory and execute) the program binary it is supposed to run.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(node_forks_total{alias=~\"$host\"}[$__range]) ",
       "legendFormat": "Forks: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    }
   ]
  },
  {
   "title": "Entropy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Entropy (bits)",
     "type": "graph",
     "description": "In computing, entropy is the randomness collected by an operating system or application for use in cryptography or other uses that require random data. This randomness is often collected from hardware sources (variance in fan noise or HDD), either pre-existing ones such as mouse movements or specially provided randomness generators. A lack of entropy can have a negative impact on performance and security.\n\nBits of available entropy.\n - Critical:\n    - If < 500 bits there is a problem.\n\n- Sometimes servers just have the weirdest SSL problems ever. In some of these situations, the entropy has been drained. Entropy is the measure of the random numbers available from /dev/urandom, and if you run out, you can’t make SSL connections. \n- To check the status of your server’s entropy, just run the following: $ cat /proc/sys/kernel/random/entropy_avail\n- The consensus is that numbers below 1000 will lead to processes blocking waiting for more entropy.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": "node_entropy_available_bits{alias=~\"$host\"}",
       "legendFormat": "Entropy: {{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load: 1m",
     "type": "graph",
     "description": "- Load average – is the average system load calculated over a given period of time of 1, 5 and 15 minutes.\n   - In Linux, the load-average is technically believed to be a running average of processes in it’s (kernel) execution queue tagged as running or uninterruptible.\n  - Linux load averages track not just runnable tasks, but also tasks in the uninterruptible sleep state.\n\nLoad for 1m > 2 means a possible problem.\n>Actual Treshold is 6.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_load1{alias=~\"$host\"} ",
       "legendFormat": "Load1: {{alias}}"
      }
     ]
    },
    {
     "title": "Load: 5m",
     "type": "graph",
     "description": "- Load average – is the average system load calculated over a given period of time of 1, 5 and 15 minutes.\n   - In Linux, the load-average is technically believed to be a running average of processes in it’s (kernel) execution queue tagged as running or uninterruptible.\n  - Linux load averages track not just runnable tasks, but also tasks in the uninterruptible sleep state.\n\nLoad for 1m > 2 means a possible problem.\n>Actual Treshold is 6.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "node_load5{alias=~\"$host\"}",
       "legendFormat": "Load5: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_load1%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%223601s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Afalse%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Load: 15m",
     "type": "graph",
     "description": "- Load average – is the average system load calculated over a given period of time of 1, 5 and 15 minutes.\n   - In Linux, the load-average is technically believed to be a running average of processes in it’s (kernel) execution queue tagged as running or uninterruptible.\n  - Linux load averages track not just runnable tasks, but also tasks in the uninterruptible sleep state.\n\nLoad for 1m > 2 means a possible problem.\n>Actual Treshold is 6.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_load15{alias=~\"$host\"}",
       "legendFormat": "Load15: {{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "vCPU / Instance",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{alias=~\"$host\"}) without (mode,instance,job)) without (cpu) ",
       "legendFormat": "vCPU / Instance"
      }
     ]
    },
    {
     "title": "CPU Used",
     "type": "graph",
     "description": "Used CPU from a total available of 100%.\n- CPUThreshold:\n >Critical: > 90% Used CPU\n\nThere are 3 general states your CPU can be in:\n - Idle, which means it has nothing to do.\n - Running a user space program, like a command shell, an email server, or a compiler.\n - Running the kernel, servicing interrupts or managing resources.\n\nThese three meta states can be further subdivided. For example, user space programs can be categorized as those running under their initial priority level or those running with a nice priority. Niceness is a way to tweak the priority level of a process so that it runs less frequently. The niceness level ranges from -20 (most favorable scheduling) to 19 (least favorable). By default processes on Linux are started with a niceness of 0.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - (avg by(env, job) (irate(node_cpu_seconds_total{mode=\"idle\",alias=~\"$host\"}[$__range])) * 100) ",
       "legendFormat": "CPU: {{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Used",
     "type": "graph",
     "description": "Used Memory from a total available of 100%.\n- Memory Threshold:\n >Critical: > 85% Used Memory",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(((node_memory_MemTotal_bytes{alias=~\"$host\"} - node_memory_MemFree_bytes{alias=~\"$host\"} - node_memory_Cached_bytes{alias=~\"$host\"} - node_memory_Buffers_bytes{alias=~\"$host\"}) / (node_memory_MemTotal_bytes{alias=~\"$host\"})) * 100)",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Swap Used",
     "type": "graph",
     "description": "Used Swap from a total available of 100%.\n- Swap Threshold:\n >Critical: > 75% Used Swap\n\nJust as Linux uses free memory for purposes such as buffering data from disk, there eventually is a need to free up private or anonymous pages used by a process. These pages, unlike those backed by a file on disk, cannot be simply discarded to be read in later. Instead they have to be carefully copied to backing storage, sometimes called the swap area.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(((node_memory_SwapTotal_bytes{alias=~\"$host\"} - node_memory_SwapFree_bytes{alias=~\"$host\"}) / node_memory_SwapTotal_bytes{alias=~\"$host\"}) * 100)",
       "legendFormat": "Swap: {{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O Utilisation",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_io_time_seconds_total{alias=~'$host',device!~'^(md\\\\\\\\d+$|dm-)'}[5m])",
       "legendFormat": "Disk I/O Utilisation:  {{alias}} [{{device}}]"
      }
     ]
    },
    {
     "title": "Disk IOPs",
     "type": "graph",
     "description": "Reads + Writes = Total.\n- Critical:\n  - If > 850 iops then there is a High Load.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "sum by(alias, env) (rate(node_disk_reads_completed_total{alias=~\"$host\"}[5m]) + rate(node_disk_writes_completed_total{alias=~\"$host\"}[5m]))",
       "legendFormat": "IOPs: {{alias}}"
      }
     ]
    },
    {
     "title": "Disk Write Latency (ms)",
     "type": "graph",
     "description": "DISK seconds Read/ Write Latency.\n- Critical:\n  - Recommended performance value is < 10ms as avg value of the Avg Disk sec/Read,Write.\n  - Critical value of the Avg Disk sec/Read,Write is > 50ms, should not exceed this value.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_write_time_seconds_total{alias=~\"$host\"}[5m])/ rate(node_disk_writes_completed_total{alias=~\"$host\"}[5m]))",
       "legendFormat": "Disk Write Latency: {{alias}} [{{device}}]"
      }
     ]
    },
    {
     "title": "Disk Read Latency (ms)",
     "type": "graph",
     "description": "Disk seconds Read Latency.\n- Critical:\n  - Recommended performance value is < 10ms as avg value of the Avg Disk sec/Read,Write.\n  - Critical value of the Avg Disk sec/Read,Write is > 50ms, should not exceed this value.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_read_time_seconds_total{alias=~\"$host\"}[5m])/ rate(node_disk_reads_completed_total{alias=~\"$host\"}[5m]))",
       "legendFormat": "Disk Read Latency: {{alias}} [{{device}}]"
      }
     ]
    },
    {
     "title": "Disk Throughput",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{alias=~\"$host\"}[5m]) + irate(node_disk_written_bytes_total{alias=~\"$host\"}[5m])",
       "legendFormat": "Disk Troughput: {{alias}} [{{device}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filesystem Device Error",
     "type": "graph",
     "description": "Whether an error occurred while getting statistics for the given device.\n> A value > 0 Means that there are some problems with that device.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_device_error{alias=~\"$host\"} ",
       "legendFormat": "Filesystem Device Error: {{alias}} {{fstype}} {{device}} {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Filesystem Space Used",
     "type": "graph",
     "description": "Filesystem used space.\n> If is > 80% then is Critical.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "((node_filesystem_size_bytes{alias=~\"$host\"} - node_filesystem_avail_bytes{alias=~\"$host\"}) / node_filesystem_size_bytes{alias=~\"$host\"}) * 100",
       "legendFormat": "Filesystem Space Used: {{alias}} {{fstype}} {{device}} {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Filesystem Inodes Used",
     "type": "graph",
     "description": "Filesystem used file nodes.\n> If is > 85% the is Critical.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_files_free{alias=~\"$host\"} / node_filesystem_files{alias=~\"$host\"}",
       "legendFormat": "Filesystem Inodes: {{alias}} {{fstype}} {{device}} {{mountpoint}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "File Descriptors Used",
     "type": "graph",
     "description": "A file descriptor is a data structure used by a program to get a handle on a file, the most well know being 0,1,2 for standard in, standard out, and standard error.\n\nThe maximum number of file handles denotes the maximum number of open files on a Linux system.\n\nThe kernel dynamically allocates file handles whenever a file handle is requested by an application but the kernel does not free these file handles when they are released by the application. The kernel recycles these file handles instead. This means that over time the total number of allocated file handles will increase even though the number of currently used file handles may be low.\n\n>$ cat /proc/sys/fs/file-nr\n\n    1376    0       785623\n\n- 1376: total allocated file descriptors (the number of file descriptors allocated since boot)\n- 0: total free allocated file descriptors\n- 785623: maximum open file descriptors [the maximum file handles that can be allocated (also found in /proc/sys/fs/file-max)]\n\n1376 - 0 = 1376 (being used)",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "(node_filefd_allocated{alias=~\"$host\"} / node_filefd_maximum{alias=~\"$host\"}) * 100",
       "legendFormat": "File Descriptors Used: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_procs_running%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%2243200s%22%2C%22end_input%22%3A%222015-9-18%2013%3A46%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Process Open Files Used",
     "type": "graph",
     "description": "Open Files Limits.\n- Critical:\n   - If > 85% then there is High Usage.\n\nprocess_open_fds\t\n>Number of open file descriptors.\t\n\nprocess_max_fds\t\n> Maximum number of open file descriptors.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(process_open_fds{alias=~\"$host\"} / process_max_fds{alias=~\"$host\"}) * 100",
       "legendFormat": "Open Files Used: {{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Interface State",
     "type": "graph",
     "description": "Thresholds:\n- Critical if state = DOWN (0)",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_network_up{alias=~\"$host\",interface!=\"lo\"}",
       "legendFormat": "Interface: {{alias}} [{{interface}}] {{operstate}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Network IN/OUT Drops",
     "type": "graph",
     "description": "Network Drops.\n- Critical:\n   - If  is > 0 then are Drops on that interface (IN/OUT) and is not ok.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_receive_drop_total{alias=~\"$host\",device!=\"lo\"}[5m]) ",
       "legendFormat": "IN: {{device}}: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_transmit_drop_total{alias=~\"$host\",device!=\"lo\"}[5m]) ",
       "legendFormat": "OUT: {{device}}: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Network IN/OUT Errors",
     "type": "graph",
     "description": "Network Errors on IN/OUT.\n- Critical:\n  - If Errors > 0 then there are some problems on that interface.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_receive_errs_total{alias=~\"$host\",device!=\"lo\"}[5m]) ",
       "legendFormat": "IN: {{ device }}: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_transmit_errs_total{alias=~\"$host\",device!=\"lo\"}[5m]) ",
       "legendFormat": "OUT: {{ device }}: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Network IN/OUT Traffic",
     "type": "graph",
     "description": "IN/ OUT Traffic rate.\n- Critical:\n  - If IN/OUT traffic = 0% from a total of 100% possible on that interface there is Low Bandwidth or interface problem.\n  - If IN/OUT traffic > 95% from a total of 100% possible on that interface there is High Bandwidth.\n\n95% (0.95 x 1e+09 =0.95 x 1 x 10^9 = 0.884756 GB, Gigabytes) supposing that the interface is 1 GB.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_receive_bytes_total{alias=~\"$host\",device!=\"lo\"}[5m]) ",
       "legendFormat": "IN: {{ device }}: {{alias}} ",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_transmit_bytes_total{alias=~\"$host\",device!=\"lo\"}[5m]) * -1",
       "legendFormat": "OUT: {{ device }}: {{alias}} ",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Network IN/OUT Packets",
     "type": "graph",
     "description": "Network Packets for IN/OUT.\n- Critical:\n   - If  is = 0 for IN/OUT.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_receive_packets_total{alias=~\"$host\",device!=\"lo\"}[5m])",
       "legendFormat": "IN: {{device}}: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      },
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_network_transmit_packets_total{alias=~\"$host\",device!=\"lo\"}[5m]) * -1",
       "legendFormat": "OUT: {{device}}: {{alias}}",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemTotal%7Balias%3D%5C%22%24host%5C%22%7D%20-%20(node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D)%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Network MTU (bytes)",
     "type": "graph",
     "description": "Network MTU:\n- In computer networking, the maximum transmission unit (MTU) is the size of the largest protocol data unit (PDU) that can be communicated in a single network layer transaction. The MTU relates to, but is not identical to the maximum frame size that can be transported on the data link layer, e.g. Ethernet frame.\n- Larger MTU is associated with reduced overhead. Smaller MTU values can reduce network delay. In many cases, MTU is dependent on underlying network capabilities and must be adjusted manually or automatically so as to not exceed these capabilities. MTU parameters may appear in association with a communications interface or standard. Some systems may decide MTU at connect time.\n\n- MTUs apply to communications protocols and network layers. The MTU is specified in terms of bytes or octets of the largest protocol data unit that the layer can pass onwards. MTU parameters usually appear in association with a communications interface (NIC, serial port, etc.). Standards (Ethernet, for example) can fix the size of an MTU; or systems (such as point-to-point serial links) may decide MTU at connect time.\n\n- Underlying data link and physical layers usually add overhead to the network layer data to be transported, so for a given maximum frame size of a medium one needs to subtract the amount of overhead to calculate that medium's MTU. For example, with Ethernet, the maximum frame size is 1518 bytes, 18 bytes of which are overhead (header and FCS), resulting in an MTU of 1500 bytes.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_network_mtu_bytes{alias=~\"$host\",interface!=\"lo\"}",
       "legendFormat": "MTU: {{alias}} [{{interface}}]",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    },
    {
     "title": "Network Interface Speed",
     "type": "graph",
     "description": "- node_network_transmit_queue_length = transmit_queue_length value of /sys/class/net/<iface>.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_network_transmit_queue_length{alias=~\"$host\",interface!=\"lo\"}",
       "legendFormat": "MTU: {{alias}} [{{interface}}]",
       "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22node_memory_MemFree%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Buffers%7Balias%3D%5C%22%24host%5C%22%7D%20%2B%20node_memory_Cached%7Balias%3D%5C%22%24host%5C%22%7D%22%2C%22range_input%22%3A%22900s%22%2C%22end_input%22%3A%222015-10-22%2015%3A25%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
      }
     ]
    }
   ]
  },
  {
   "title": "NTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "NTP Sanity",
     "type": "graph",
     "description": "- Critical:\n   - If > 0 then the health of NTP is affected.\n\n- Aggregate NTPD health including stratum, leap flag, sane freshness, root distance being less than collector.ntp.max-distance and causality violation being less than collector.ntp.local-offset-tolerance.\n- Causality violation is lower bound estimate of clock error done using SNTP, it's calculated as positive portion of abs(node_ntp_offset) - node_ntp_rtt / 2.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_ntp_sanity{alias=~\"$host\"}",
       "legendFormat": "NTP Sanity: {{alias}}"
      }
     ]
    },
    {
     "title": "NTP Leap Seconds",
     "type": "graph",
     "description": "- System NTP Leap Seconds > 0, where 0 – OK, 1 – add leap second at UTC midnight, 2 – delete leap second at UTC midnight, 3 – unsynchronised.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "node_ntp_leap{alias=~\"$host\"}",
       "legendFormat": "NTP Leap Seconds: {{alias}}"
      }
     ]
    },
    {
     "title": "NTP Stratum",
     "type": "graph",
     "description": "- The stratum is a measure for synchronization distance. Opposed to jitter or delay the stratum is a more static measure. Basically (and from the perspective from a client) it is the number of servers to a reference clock. So a reference clock itself appears at stratum 0, while the closest servers are at stratum 1. On the network there is no valid NTP message with stratum 0.\n- A server synchronized to a stratum n server will be running at stratum n + 1. The upper limit for stratum is 15. The purpose of stratum is to avoid synchronization loops by preferring servers with a lower stratum.\n- NTP Stratum levels up to 15 are valid Stratum Levels. In Network Time Protocol (NTP), Stratum-16 is used to indicate that a device time is not synchronized.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_ntp_stratum{alias=~\"$host\"}",
       "legendFormat": "NTP Stratum: {{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processes: Threads Used",
     "type": "graph",
     "description": "Used THREADS from a total available of 100%.\n- THREADS Threshold:\n >Critical: > 85% Used THREADS",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(node_processes_threads{alias=~\"$host\"} / node_processes_max_threads{alias=~\"$host\"}) * 100",
       "legendFormat": "Threads Used: {{alias}}"
      }
     ]
    },
    {
     "title": "Processes: State",
     "type": "graph",
     "description": "PROCESS STATE CODES:\n   - R  running or runnable (on run queue)\n   - D  uninterruptible sleep (usually IO)\n   - S  interruptible sleep (waiting for an event to complete)\n    - Z  defunct/zombie, terminated but not reaped by its parent\n    - T  stopped, either by a job control signal or because it is being traced\n\n- Find and kill Zombie:\n  - $ ps aux | awk {'print $8'}|grep -c Z\n  - $ ps aux | awk '{ print $8 \" \" $2 }' | grep -wc Z\n  - $ ps aux |grep \"defunct\" OR ps aux |grep Z\n  - $ ps aux | awk '{ print $8 \" \" $2 }' | grep -w Z\n  - $ ps aux | grep Z\n  >Kill: \n   - $ kill -s SIGCHLD pid (pid = id parent process)\n   - $ pstree -process and $ kill -9 pid (pid parent process)",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_processes_state{alias=~\"$host\"}",
       "legendFormat": "Processes State  (  {{state}} ):  {{alias}}"
      }
     ]
    },
    {
     "title": "Nr. Processes: Running & Blocked",
     "type": "graph",
     "description": "kernel/system statistics:\n- Number of processes in runnable state.  (Linux 2.5.45 onward.)\n-   Number of processes blocked waiting for I/O to complete.  (Linux 2.5.45 onward.)",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "node_procs_blocked{alias=~\"$host\"}",
       "legendFormat": "Processes Blocked:  {{alias}}"
      },
      {
       "expr": "node_procs_running{alias=~\"$host\"}",
       "legendFormat": "Processes Running:  {{alias}}"
      }
     ]
    }
   ]
  }
 ]
}